import { jsPDF } from "jspdf";

function DownloadReport({ score, strengths, improvements }) {
  const download = () => {
    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.text("CareerPilot AI", 20, 20);

    doc.setFontSize(16);
    doc.text("Resume Analysis Report", 20, 35);

    doc.setFontSize(14);
    doc.text(`ATS Score: ${score}%`, 20, 55);

    doc.text("Strengths", 20, 75);

    let y = 85;

    strengths.forEach((item) => {
      doc.text(`• ${item}`, 25, y);
      y += 10;
    });

    y += 10;

    doc.text("Improvements", 20, y);

    y += 10;

    improvements.forEach((item) => {
      doc.text(`• ${item}`, 25, y);
      y += 10;
    });

    y += 20;

    doc.setFontSize(12);
    doc.text("Generated by CareerPilot AI", 20, y);

    doc.save("CareerPilot_Report.pdf");
  };

  return (
    <button
      onClick={download}
      className="bg-green-600 hover:bg-green-700 text-white px-6 py-3 rounded-xl mt-8"
    >
      Download Report
    </button>
  );
}

export default DownloadReport;
